### ISSUE TITLE
node-fetch-server - ability to call `next` in `onError`

### ISSUE THREAD

**Issue by rossrobino** [mjackson/remix-the-web#13]
I'm trying to use the `createRequestListener` in a Vite plugin in the `configureServer` hook. I would like Vite to handle if there is an error instead of sending the default `internalServerError`. 

I think something like this might make sense.

```ts
let response: Response;
try {
	response = await handler(request, client);
} catch (error) {
	try {
		let errorResponse = await onError(error);
		// handled in Vite middleware by calling `next(error)` within `onError`
		if (!errorResponse) return;
		response = errorResponse;
	} catch (error) {
		console.error(`There was an error in the error handler: ${error}`);
		response = internalServerError();
	}
}
```

Currently, I'm getting this error. I think this is because Vite has already sent back the response when I call `next(error)` in my `onError` handler.  

```bash
Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:342:11)
```

I'm excited about this repo of packages! Thanks for making these available.

**Comment by mjackson** [comment]
I checked the `configureServer` docs and it looks like this package and that one overlap in responsibilities. The only examples I could find there are adding middleware to an existing server they have already created for you, but this package isn't intended to be used as a middleware in another server. It *is* the server, and by that I mean it is responsible for sending the response, not delegating it to another server.

If you're just trying to use the `Request` interface in the rest of your middleware stack, you might wanna just copy/paste the `createRequest` function out of the source and roll your own fetch handler interface.

> I'm excited about this repo of packages! Thanks for making these available.

You're welcome! 🙌

**Comment by rossrobino** [comment]
Got it, makes sense. Yeah I'm trying to use it middleware in this case. 

Ok, I copied and made the change above and it is working as expected now. In case anyone runs into this and wants to do something similar here's where it's used in the plugin: https://github.com/rossrobino/domco/blob/8b873f1dbdd667eedd96867b6581eaed5067df15/packages/domco/src/plugin/configure-server/index.ts#L51

Thanks for looking into it.
