### ISSUE TITLE
Are you open to a `.merge` method PR?

### ISSUE THREAD

**Issue by gustavoguichard** [mjackson/remix-the-web#20]
Hey @mjackson , thank you for building this awesome package!

I created the [make-service](https://github.com/gustavoguichard/make-service) lib which extends the native `fetch` to improve its DX, and in the process I had to create a `mergeHeaders` function that is used internally and I ended up exporting it.
It turns out I'm often using that method when working with headers in other contexts, so I import it from the lib. I recon it would be a nice addition to this lib given it aims to improve the overall Headers DX.

Would you be interested in a PR that implements such functionality?

This is the API I have in mind:

```ts
let headers = new Headers({ 'Content-Type': 'text/html', 'Accept-Language': 'en-US,en;q=0.9' })
headers.merge(new Headers({ 'Content-Type': 'application/json', 'X-API-Key': 'secret' }))
console.log(`${headers}`)
// Content-Type: application/json
// X-Api-Key: secret-key
// Accept-Language: en-US,en;q=0.9

// It also accepts anything from `HeadersInit` type
headers.merge({ 'content-type': 'application/json', 'X-API-Key': 'secret' })
headers.merge([['content-type', 'application/json'], ['X-API-Key', 'secret']])
```

LMK if it fits the scope of this lib, it is a [fairly simple implementation](https://github.com/gustavoguichard/make-service/blob/main/src/primitives.ts#L55-L82) and I'd be glad to contribute 🤙

**Comment by mjackson** [comment]
Hey @gustavoguichard! It's good to hear from you.

This feels a little out of scope for the mjackson/headers lib, tbh. I'm trying to limit the scope to augmenting the base `Headers` interface with property-style accessors, but nothing more. But it does sound like a perfect little addition you could make in your own lib if you'd like.

**Comment by gustavoguichard** [comment]
All good, it is already in my library but I agree it looks slightly beyond scope 👌🏽
Always glad to interact 🙏🏽
