### ISSUE TITLE
Collaborate with other development teams to implement packages

### ISSUE THREAD

**Issue by Bricklou** [mjackson/remix-the-web#22]
Under advice from Jacob Paris on the Discord server, I'm rewriting [my message](https://discord.com/channels/770287896669978684/770287896669978687/1288466385885728840) here to have a better visibility.

After having watched the remix roadmap 15, and I had some though about the `file-storage` package. I am wondering : Romain Lanz and Harminder Virk from Adonis created [FlyDrive](https://flydrive.dev/docs/introduction) (the new drive library for Adonis, but it is completely framework-agnostic) to handle file storing server side, isn't it overlapping the library this repository ? 🤔

FlyDrive VS file-storage is a simple example, but the Adonis team made a lot of small packages that could work in a remix environment, like [VineJS](https://vinejs.dev) for validation.

I'm aware that some libraries might not fit the "remix-way", but I am rather thinking about a collaboration between both Adonis and Remix teams to create an ecosystem of packages that would fit to everyone. This way, we can avoid reimplementing things again and again.

(This issue can be migration into a GitHub discussion if needed.)

**Comment by mjackson** [comment]
I'm happy to collaborate with anyone who wants to collaborate with us. That's why I'm working out in the open on GitHub and publishing everything as I go. I plan on drawing up a roadmap soon so it's more obvious where we're going with this, but in the meantime the Adonis team (or any other team) are free to fork/PR away!
