### ISSUE TITLE
Cannot read part metadata

### ISSUE THREAD

**Issue by heivo** [mjackson/remix-the-web#23]
Hi,

when I try to read part metadata that is extracted from headers it always returns undefined:

```ts
for await (const part of parseMultipartRequest(request)) {
  console.log(part.name) // -> undefined
}
```

I added some console.log statements to `MultipartPart` in node_modules like this
```ts
export class MultipartPart {
    // ...
    get name() {
        console.log(this.headers)
        console.log(this.headers.contentDisposition)
        return this.headers.contentDisposition.name;
    }
}
```
This prints:
```
{
  'content-disposition': 'form-data; name="file1"; filename="hello.txt"',
  'content-type': 'text/plain'
}
ContentDisposition {
  filename: undefined,
  filenameSplat: undefined,
  name: undefined,
  type: undefined
}
```

I think parsing of the headers is not working properly.

Using this in a Remix resource route and uploading a file with curl:

```bash
curl -F "file1=@hello.txt" http://localhost:3000/api/upload
```

**Comment by heivo** [comment]
I think it's caused by overriding the `append(name, value)` method in `SuperHeaders`, the method is never called from the constructor. When I rename the method to something else it's working fine.

**Comment by mjackson** [comment]
Are you using `installGlobals` in Remix? If so, stop using it. It breaks this behavior by overwriting the global Headers object with one that doesn't follow the spec.

**Comment by heivo** [comment]
Yes I do, thanks for the hint, will try it :+1:

**Comment by heivo** [comment]
It worked, thanks alot! Maybe worth mentioning that in the docs?
