### ISSUE TITLE
How to work with stored file?

### ISSUE THREAD

**Issue by kunanyi** [mjackson/remix-the-web#25]
(Apologies, I'd of put this in a Discussion normally, as it's more a gap in my understanding)

Re:file storage:

Using _edgefirst-dev/r2-file-storage_ I can get a CSV file stored

However I don't understand how to access the data in the CSV file?

"storage.get" seems to just retrieve the meta data for the file? What if I wanted to load and parse the CSV contents?

I'm not sure if that is the remit of this library?  But was hoping for a straight forwards "remixy" way to do this simple thing

**Comment by sergiodxa** [comment]
Once you have a File instance if you need the content you can do `await file.text()` or any other standard method of File objects.

This method is inherited from the Blob class that File extends from https://developer.mozilla.org/en-US/docs/Web/API/Blob/text.

**Comment by kunanyi** [comment]
Awesome thank you!

**Comment by kmvan** [comment]
```typescript
const formData = await parseFormData(request, uploadHandler)
const file = formData.get('file') as File
const text = await file.text()
```
