### ISSUE TITLE
@mjackson/headers@workspace:^

### ISSUE THREAD

**Issue by shmuli9** [mjackson/remix-the-web#36]
ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@mjackson/headers@workspace:^" is in the dependencies but no package named "@mjackson/headers" is present in the workspace

This error happened while installing the dependencies of edgekitjs@0.0.47
 at @mjackson/form-data-parser@0.5.0
 at @mjackson/multipart-parser@0.7.1

**Comment by wookets** [comment]
This broke my npm install as well. Needed to rollback to 0.4.0.

**Comment by nicksrandall** [comment]
@mjackson There seems to be an issue with your publish to npm script because your package.json still has references to your workspace. This breaks installs.

**Comment by Bessonov** [comment]
Duplicate of #34 .

**Comment by ryanflorence** [comment]
you can workaround it until it gets fixed

https://github.com/mjackson/remix-the-web/issues/34#issuecomment-2537453371

**Comment by mjackson** [comment]
Sorry about the bad publish, everyone. Should be fixed now.

https://github.com/mjackson/remix-the-web/releases/tag/multipart-parser%400.7.2

https://github.com/mjackson/remix-the-web/releases/tag/form-data-parser%400.5.1

**Comment by shmuli9** [comment]
Legend @mjackson 
Thanks for all your work

**Comment by mattoni** [comment]
This appears to be happening again @mjackson. 

```
 ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In ../..: "@mjackson/headers@workspace:^" is in the dependencies but no package named "@mjackson/headers" is present in the workspace

This error happened while installing the dependencies of @mjackson/multipart-parser@0.8.0
``
